[build]
builder = "nixpacks"
buildCommand = ""

[deploy]
startCommand = "php -S 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[phases.setup]
nixPkgs = ["php82"]
